config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/home', to:'pages#index'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: :new
  get '/register', to:'chefs#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef <ApplicationRecord
  has_many :recipes
  has_many :likes

  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { minimum: 5, maximum: 40 }
  VALID_REG_EXPR = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
              uniqueness: { case_sensitive: false }, 
              format: { with: VALID_REG_EXPR }
  has_secure_password

end

app/models/like.rb
class Like <ApplicationRecord
  belongs_to :chef
  belongs_to :recipe

  validates_uniqueness_of :chef, scope: :recipe

end

app/models/recipe.rb
class Recipe <ApplicationRecord
  belongs_to :chef, dependent: :destroy
  has_many :likes

  validates :name, presence: true, length: { minimum: 3, maximum: 40}
  validates :description, presence: true, length: { minimum: 3, maximum: 250}
  validates :summary, presence: true, length: { minimum: 3, maximum: 100}
  validates :chef_id, presence: true
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> { order(updated_at: :DESC) }


  def thumbs_up_total
    self.likes.where(like: true).size

  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||=  Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_user
  end


  def require_valid_session
    if !logged_in?
      flash[:danger] = "Please login to access the application"
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

    before_action :require_valid_session

    before_action :require_same_user, only: [ :edit, :update]

    def index
        @chefs = Chef.paginate(:page => params[:page], :per_page=>3)
    end

    def show
        @chef = Chef.find(params[:id])
        @recipes = @chef.recipes.paginate(:page => params[:page], :per_page => 3)
    end

    def new

        @chef = Chef.new
    end

    def create

        @chef=Chef.new(chef_params)

        if @chef.save
            flash[:success] = "Chef Profile has been created successfully"
            session[:chef_id] = @chef.id
            redirect_to recipes_path
        else
            render :new
        end

    end

    def edit
        @chef = Chef.find(params[:id])
    end

    def update
        @chef = Chef.find(params[:id])

        if @chef.update(chef_params)
            flash[:success] = "Your Profile has been updated successfully"
            redirect_to chef_path(@chef)
        else
            render :edit
        end
    end

    def require_same_user
        if current_user != @chef
            flash[:danger] = "You can only edit your profile"
            redirect_to root_path
        end
    end


    private

    def chef_params
        params.require(:chef).permit(:chefname,:email,:password)
    end

end

app/controllers/logins_controller.rb
class LoginsController <ApplicationController

  def new

  end

  def create
    chef = Chef.find_by_email(params[:email])

    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = "You are logged in"
      redirect_to recipes_path
    else
      flash[:danger] = "Your email address or pasword does not match"
      render :new
    end

  end

  def destroy
    session[:chef_id]=nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to recipes_path if logged_in?
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [ :edit, :update, :show, :like ]
  before_action :require_valid_session, except: [ :index, :show ]
  before_action :require_same_user, only: [ :edit, :update ]

  def index
   # @recipes = Recipe.all.sort_by{|likes| likes.thumbs_up_total}.reverse
    @recipes = Recipe.paginate(:page => params[:page], :per_page => 4)
  end

  def show
    #@recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef  = current_user

    if @recipe.save
      #do something
      flash[:success] = "Your recipe was created successfully!"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    #@recipe = Recipe.find(params[:id])
  end

  def update
    #@recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      flash[:success] = "You recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def like
    #@recipe = Recipe.find( params[:id])

    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_back(fallback_location: recipes_path)
    else
      flash[:danger] = "You can only like or dislike recipe once"
      redirect_back(fallback_location: recipes_path)
    end

  end

  def set_recipe
    @recipe = Recipe.find( params[:id])
  end

  def require_same_user
    if current_user != @recipe.chef
      flash[:danger] = "You can only edit your recipes"
      redirect_to root_path
    end
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name,:summary,:description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef,options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chefs/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2" >
    <%= form_for @chef  do |f| %>
        <%= f.label :chefname %>
        <%= f.text_field :chefname %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password, rows: 10 %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit(@chef.new_record? ? "Create Chef Profile" : "Edit Chef Profile", class:"btn btn-success") %>
    <% end %>
  </div>

app/views/chefs/edit.html.erb
<%= render '/shared/page_title', title: 'Edit Profile' %>

<%= render '/shared/error', obj: @chef %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All chefs" %>
<ul class="nav nav-tabs">
  <li>
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li class="active">
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<div class="row" >
   <div class="col-sm-4 col-sm-offset-4 center">
        <%= will_paginate %>
    </div>
</div>

<% @chefs.each do |chef| %>
    <div class="row" >
       <div class="col-sm-4 center">
            <%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
        </div>
        <div class=" col-sm-8 center well">
            <p><h3><%= chef.chefname %></h3></p>
            <p><h5><%= chef.email %></h5></p>
            <p> Created:  <%= time_ago_in_words(chef.created_at) %> ago</p>
            <p> Updated:  <%= time_ago_in_words(chef.updated_at) %> ago</p>
        </div>
    </div>
    <hr/>
<% end %>

app/views/chefs/new.html.erb
<%= render '/shared/page_title', title: 'Register Your Profile' %>

<%= render '/shared/error', obj: @chef %>
<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render '/shared/page_title', title: @chef.chefname %>

<div class="row">

  <div class="col-sm-4 col-sm-offset-4 center">
    <%= gravatar_for @chef, size: 100 %>
    <hr/>
  </div>

</div>

<div class="row">

  <div class="col-sm-4 col-sm-offset-4 center">
    <h5>Recipes</h5>
    <%= will_paginate @recipes %>
  </div>

</div>


<% @recipes.each do |recipe| %>
    <div class="row">

      <div class="col-sm-8 well">
        <h4> <%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= recipe.summary %> </p>
        <p>
           <span class='quiet'> created: <%= time_ago_in_words(recipe.updated_at) %> ago,  </small>
          </span>

          <span class='quiet'> updated: <%= time_ago_in_words(recipe.updated_at) %> ago </small>
          </span>
        </p>
        <div class="pull-right">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
              <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipe.thumbs_up_total %>
          <% end %>
          &nbsp&nbsp&nbsp&nbsp
          <%= link_to like_recipe_path(recipe, like: false), method: :post  do %>
              <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= recipe.thumbs_down_total %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-4 pull-right">
        <%= image_tag(recipe.picture.url, size: "150x150", class: "gravatar") if recipe.picture? %>
      </div>

    </div>
    <hr/>
<% end %>

<hr/>

app/views/layouts/_footer.html.erb
<div class="footer">
<p>&copy; My Recipes 2017</p>

</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-12">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"> <%= message %>
      <a class="close" data-dismiss="alert">&#215;</a>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "MY LOGO", root_path, class: "navbar-brand btn btn-lg btn-success" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li> <span><%= link_to "link2","", class: "btn btn-warning navbar-btn" %></span></li>
        <li> <span><%= link_to "link3","", class: "btn btn-warning navbar-btn" %></span></li>
        <% if logged_in? %>
          <li> <span><%= link_to "New Recipe",new_recipe_path, class: "btn btn-warning navbar-btn" %></span></li>
        <% end %>
      </ul>

      <% if logged_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown"  do %>
             <%= current_user.chefname %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile",chef_path(current_user) %></li>
              <li><%= link_to "Edit Profile",edit_chef_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout",logout_path, class: "glyphicon glyphicon-log-out" %></li>
            </ul>
          </li>
        </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Singin",login_path, class: "glyphicon glyphicon-log-in" %></li>
          </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/navigation' %>
  <body>
  <div class="container">
  <%= render 'layouts/messages' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>


  </body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Log in' %>


  <div class="row">
    <div class="well col-sm-6 col-sm-offset-3">
      <%= form_tag '/login' do %>
        <%= label_tag :email %>
        <%= text_field_tag :email %>

        <%= label_tag :password %>
        <%= password_field_tag :password %>

        <%= submit_tag "Login", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>

app/views/pages/index.html.erb
  <div class="row" >
    <div class="jumbotron">
      <h1>Welcome to my Recipies Application</h1>
      <p>This is my recipes website. You can register and upload your recipes</p>
      <p><%= link_to "Sign Up!",register_path,class: "btn btn-primary btn-lg"  %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 quite caption">
      <h3>View Recipes as Guest User</h3>
      <p>View recipes list as guest user and you can signup later</p>
      <p> <%= link_to "View Recipie Listing", recipes_path, class:"btn btn-warning" %></p>
    </div>

    <div class="col-sm-6 quite caption">
      <h3>Add/Update Recipes</h3>
      <p>Sign-in to view recipes. Sign in to create and update your recipes.</p>
      <p> <%= link_to "Sign In!" ,login_path, class:"btn btn-success" %> </p>
    </div>
  </div>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2" >
  <%= form_for(@recipe, html: { multipart: true}) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :summary %>
  <%= f.text_field :summary %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 10 %>
  
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/jpg,image/gif,image/png' %>
  </span>

  <%= f.submit(@recipe.new_record? ? "Create Recipe" : "Edit Recipe", class:"btn btn-success") %>
  <% end %>
</div>

<script type="text/javascript">
//binds to onchange event of your input field
$('#recipe_picture').bind('change', function() {

  //this.files[0].size gets the size of your file.
  file_size_in_megabytes = this.files[0].size/1024/1024;
  if (file_size_in_megabytes > 5){
    alert('Maximum file size is 5MB. Please choose a smaller file');
  }

});
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'shared/error', obj: @recipe %>


<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>
<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

  <%= will_paginate %>


  <% @recipes.each do |recipe| %>
    <div class="row">
  
      <div class="col-sm-2 col-md-2">
        <section class="chef_info center">
          <%= link_to gravatar_for(recipe.chef, size: 80), chef_path(recipe.chef)%>
          <h5>Chef name: <%= recipe.chef.chefname%></h5>
        </section>
      </div>

      <div class="col-sm-6 col-md-6 well">
        <h4> <%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= recipe.summary %> </p>
        <p>
           <span class='quiet'> created: <%= time_ago_in_words(recipe.updated_at) %> ago,  </small>
          </span>

          <span class='quiet'> updated: <%= time_ago_in_words(recipe.updated_at) %> ago </small>
          </span>
        </p>
        <div class="pull-right">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
              <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipe.thumbs_up_total %>
          <% end %>
          &nbsp&nbsp&nbsp&nbsp
          <%= link_to like_recipe_path(recipe, like: false), method: :post  do %>
              <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= recipe.thumbs_down_total %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-4 pull-right">
        <%= image_tag(recipe.picture.url, size: "150x150", class: "gravatar") if recipe.picture? %>
      </div>

    </div>
  <hr/>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a Recipe" %>

<%= render 'shared/error', obj: @recipe %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %> 

<div class="row">
  <div class="col-sm-4 col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size: 100), chef_path(@recipe.chef)%>
    <p>
      Brought you by <%= @recipe.chef.chefname %>
    </p>
  </div>

  <div class="col-sm-8 col-md-8">
    <% if logged_in? and @recipe.chef == current_user %>
      <%= link_to "Edit Recipe",edit_recipe_path,class: "btn btn-small btn-success pull-right" %>
    <% end %>
      <h4><%= @recipe.summary %></h4>
      <div class="show_recipe">
          <%= image_tag(@recipe.picture.url, size: '250x250',class: "gravatar") if @recipe.picture? %>
      </div>
      <div class="well">
        <p> <strong> Steps: </strong></p>
        <%= simple_format(@recipe.description) %>
        <div class="pull-right">
          <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= @recipe.thumbs_up_total %>
          <% end %>
          &nbsp&nbsp&nbsp&nbsp
          <%= link_to like_recipe_path(@recipe, like: false), method: :post  do %>
              <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= @recipe.thumbs_down_total %>
          <% end %>
        </div>
      </div>
  </div>
</div>

<%= link_to "Return to the Recipes List",recipes_path, class: "btn btn-warning btn-small"%>
<hr/>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2 alert alert-danger">
    <h5> Please correct the following errors... <h5>
    <ul>
       <% obj.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
       <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<div class="page_title center">
  <h1> <%= title %> </h1>
  <hr/>
</div>